version: "3.8"
services:
  demucs:
    build:
      context: ./demucs
    volumes:
      - ./music/origin:/music/origin
      - ./music/separated:/music/separated
    tty: true
    working_dir: /music
